// lib/stats/labels.ts — the message keys of the statistics' dimensions, layers and presets,
// written out so every key the code uses can be found in it (test/node/i18n.test.ts).
// Generated with the strings; keep it in step with lib/stats/config.ts.
import type { MessageKey } from "../i18n";

export const DIMENSION_KEYS: Record<string, [MessageKey, MessageKey]> = {
  rows: ["statsDim_rows", "statsDimHint_rows"],
  time: ["statsDim_time", "statsDimHint_time"],
  dur: ["statsDim_dur", "statsDimHint_dur"],
  place: ["statsDim_place", "statsDimHint_place"],
  title: ["statsDim_title", "statsDimHint_title"],
  text: ["statsDim_text", "statsDimHint_text"],
  len: ["statsDim_len", "statsDimHint_len"],
  verdict: ["statsDim_verdict", "statsDimHint_verdict"],
  lang: ["statsDim_lang", "statsDimHint_lang"],
  struct: ["statsDim_struct", "statsDimHint_struct"],
  geom: ["statsDim_geom", "statsDimHint_geom"],
  expo: ["statsDim_expo", "statsDimHint_expo"],
  scroll: ["statsDim_scroll", "statsDimHint_scroll"],
  input: ["statsDim_input", "statsDimHint_input"],
  state: ["statsDim_state", "statsDimHint_state"],
  tabs: ["statsDim_tabs", "statsDimHint_tabs"],
  nav: ["statsDim_nav", "statsDimHint_nav"],
  engine: ["statsDim_engine", "statsDimHint_engine"],
  ui: ["statsDim_ui", "statsDimHint_ui"],
  device: ["statsDim_device", "statsDimHint_device"],
  cover: ["statsDim_cover", "statsDimHint_cover"],
};

export const LAYER_KEYS: Record<string, MessageKey> = {
  "rows.event": "statsL_rows_event",
  "rows.paragraph": "statsL_rows_paragraph",
  "rows.visit": "statsL_rows_visit",
  "rows.page": "statsL_rows_page",
  "rows.site": "statsL_rows_site",
  "rows.kind": "statsL_rows_kind",
  "rows.day": "statsL_rows_day",
  "time.ms": "statsL_time_ms",
  "time.s": "statsL_time_s",
  "time.min": "statsL_time_min",
  "time.quarter": "statsL_time_quarter",
  "time.hour": "statsL_time_hour",
  "time.day": "statsL_time_day",
  "dur.ms": "statsL_dur_ms",
  "dur.decis": "statsL_dur_decis",
  "dur.s": "statsL_dur_s",
  "dur.bins": "statsL_dur_bins",
  "dur.none": "statsL_dur_none",
  "place.url": "statsL_place_url",
  "place.nofragment": "statsL_place_nofragment",
  "place.querynames": "statsL_place_querynames",
  "place.path": "statsL_place_path",
  "place.pattern": "statsL_place_pattern",
  "place.host": "statsL_place_host",
  "place.domain": "statsL_place_domain",
  "place.none": "statsL_place_none",
  "title.full": "statsL_title_full",
  "title.short": "statsL_title_short",
  "title.none": "statsL_title_none",
  "text.full": "statsL_text_full",
  "text.head": "statsL_text_head",
  "text.sketch": "statsL_text_sketch",
  "text.hash": "statsL_text_hash",
  "text.none": "statsL_text_none",
  "len.all": "statsL_len_all",
  "len.words": "statsL_len_words",
  "len.rounded": "statsL_len_rounded",
  "len.bands": "statsL_len_bands",
  "len.none": "statsL_len_none",
  "verdict.probs": "statsL_verdict_probs",
  "verdict.probs2": "statsL_verdict_probs2",
  "verdict.words": "statsL_verdict_words",
  "verdict.flagged": "statsL_verdict_flagged",
  "verdict.none": "statsL_verdict_none",
  "lang.full": "statsL_lang_full",
  "lang.label": "statsL_lang_label",
  "lang.english": "statsL_lang_english",
  "lang.none": "statsL_lang_none",
  "struct.full": "statsL_struct_full",
  "struct.unit": "statsL_struct_unit",
  "struct.kind": "statsL_struct_kind",
  "struct.none": "statsL_struct_none",
  "geom.changes": "statsL_geom_changes",
  "geom.found": "statsL_geom_found",
  "geom.share": "statsL_geom_share",
  "geom.order": "statsL_geom_order",
  "geom.none": "statsL_geom_none",
  "expo.steps": "statsL_expo_steps",
  "expo.intervals": "statsL_expo_intervals",
  "expo.totals": "statsL_expo_totals",
  "expo.read": "statsL_expo_read",
  "expo.none": "statsL_expo_none",
  "scroll.frames": "statsL_scroll_frames",
  "scroll.tenth": "statsL_scroll_tenth",
  "scroll.second": "statsL_scroll_second",
  "scroll.episodes": "statsL_scroll_episodes",
  "scroll.visit": "statsL_scroll_visit",
  "scroll.none": "statsL_scroll_none",
  "input.pointer": "statsL_input_pointer",
  "input.positions": "statsL_input_positions",
  "input.events": "statsL_input_events",
  "input.minutes": "statsL_input_minutes",
  "input.idle": "statsL_input_idle",
  "input.none": "statsL_input_none",
  "state.changes": "statsL_state_changes",
  "state.totals": "statsL_state_totals",
  "state.none": "statsL_state_none",
  "tabs.full": "statsL_tabs_full",
  "tabs.ids": "statsL_tabs_ids",
  "tabs.none": "statsL_tabs_none",
  "nav.full": "statsL_nav_full",
  "nav.arrival": "statsL_nav_arrival",
  "nav.none": "statsL_nav_none",
  "engine.full": "statsL_engine_full",
  "engine.basic": "statsL_engine_basic",
  "engine.model": "statsL_engine_model",
  "ui.events": "statsL_ui_events",
  "ui.counts": "statsL_ui_counts",
  "ui.none": "statsL_ui_none",
  "device.exact": "statsL_device_exact",
  "device.families": "statsL_device_families",
  "device.none": "statsL_device_none",
  "cover.visit": "statsL_cover_visit",
  "cover.day": "statsL_cover_day",
  "cover.none": "statsL_cover_none",
};

export const PRESET_KEYS: Record<string, [MessageKey, MessageKey]> = {
  off: ["statsPreset_off", "statsPresetHint_off"],
  daily: ["statsPreset_daily", "statsPresetHint_daily"],
  sites: ["statsPreset_sites", "statsPresetHint_sites"],
  pages: ["statsPreset_pages", "statsPresetHint_pages"],
  paragraphs: ["statsPreset_paragraphs", "statsPresetHint_paragraphs"],
  study: ["statsPreset_study", "statsPresetHint_study"],
  full: ["statsPreset_full", "statsPresetHint_full"],
  fullText: ["statsPreset_fullText", "statsPresetHint_fullText"],
  custom: ["statsPreset_custom", "statsPresetHint_custom"],
};
