// test/node/notices.test.ts — THIRD_PARTY_NOTICES.md, checked against what it describes.
//
// The file is generated by scripts/notices.mjs from a list of components and the licence
// texts on disk. What the list says about the BUILD — which npm packages are bundled — is
// checked by the build itself (wxt.config.ts, scripts/vendor.mjs). What it says about the
// SOURCE is checked here: an attribution comment that names a third-party project the list
// does not cover fails, and so does an adaptation the list still claims after it has gone.
import { describe, expect, it } from "vitest";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { NOTICES_FILE, components, packageOfModule, render } from "../../scripts/notices.mjs";

const ROOT = join(__dirname, "..", "..");
const read = (rel: string): string => readFileSync(join(ROOT, rel), "utf8");

/** Everything that ships: the extension's source and the component package's own files. */
function shippedSources(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const name of readdirSync(join(ROOT, dir))) {
      const rel = `${dir}/${name}`;
      if (name === "node_modules" || name === ".venv" || name === "__pycache__") continue;
      if (statSync(join(ROOT, rel)).isDirectory()) walk(rel);
      else if (/\.(ts|html|css|py|sh|ps1|cs)$/.test(name) || dir === "installer") out.push(relative(ROOT, join(ROOT, rel)).split(sep).join("/"));
    }
  };
  for (const dir of ["lib", "entrypoints", "anagramd", "installer"]) walk(dir);
  return [...out, "install.sh", "install.ps1"].sort();
}

/** A repository on a code host: an address that names somebody's project. */
const PROJECT_URL = /https?:\/\/(?:www\.)?(?:github\.com|gitlab\.[a-z0-9.-]+|bitbucket\.org|codeberg\.org|sourceforge\.net|[a-z0-9.-]+\.googlesource\.com)\/[^\s"'`)<>{}\]]+/g;
const OURS = /^https?:\/\/github\.com\/CoderBak\/anagram(?:[/?#]|$)/i;

const COMPONENTS = components();
const covered = (url: string): boolean =>
  COMPONENTS.some((c) => [c.url, ...(c.urls ?? [])].some((u) => url.toLowerCase().startsWith(u.toLowerCase().replace(/\/$/, ""))));

describe(NOTICES_FILE, () => {
  it("is exactly what scripts/notices.mjs writes (run it after a version or licence changes)", () => {
    expect(existsSync(join(ROOT, NOTICES_FILE))).toBe(true);
    expect(read(NOTICES_FILE) === render(), `${NOTICES_FILE} is stale: node scripts/notices.mjs`).toBe(true);
  });

  it("covers every third-party project the shipped source names", () => {
    const uncovered: string[] = [];
    for (const rel of shippedSources()) {
      for (const m of read(rel).matchAll(PROJECT_URL)) {
        const url = m[0].replace(/[.,;:]+$/, "");
        if (!OURS.test(url) && !covered(url)) uncovered.push(`${rel} ${url}`);
      }
    }
    expect([...new Set(uncovered)].sort()).toEqual([]);
  });

  it("claims no adaptation that is no longer in the file it names", () => {
    const stale: string[] = [];
    for (const c of COMPONENTS) {
      for (const rel of c.adapted ?? []) {
        const text = existsSync(join(ROOT, rel)) ? read(rel) : "";
        if (![c.url, ...(c.urls ?? [])].some((u) => text.includes(u))) stale.push(`${c.name}: ${rel}`);
      }
    }
    expect(stale).toEqual([]);
  });

  it("gives every entry a licence, a copyright line and what of it Anagram contains", () => {
    for (const c of COMPONENTS) {
      expect(c.licence.length, c.name).toBeGreaterThan(2);
      expect(c.copyright.length, c.name).toBeGreaterThan(5);
      expect(c.where.length, c.name).toBeGreaterThan(10);
      expect(c.url, c.name).toMatch(/^https:\/\//);
    }
  });

  it("names our own source, a vendored package and a bundler helper apart", () => {
    expect(packageOfModule(join(ROOT, "lib", "hash.ts"))).toBeNull();
    expect(packageOfModule("lib/surfaces/chunk.ts")).toBeNull();
    expect(packageOfModule("\0anagram:en-messages")).toBeNull();
    expect(packageOfModule(`${ROOT}/node_modules/@floating-ui/dom/dist/floating-ui.dom.mjs`)).toBe("@floating-ui/dom");
    expect(packageOfModule("../../node_modules/defuddle/dist/index.js")).toBe("defuddle");
    expect(packageOfModule("\0vite/preload-helper.js")).toBe("vite");
    expect(packageOfModule("\0rolldown/runtime.js")).toBe("rolldown");
    expect(packageOfModule("virtual:wxt-background-entrypoint")).toBe("wxt");
    expect(packageOfModule("virtual:somebody-else")).toMatch(/unknown module/);
  });
});
