// test/node/pdf-route.test.ts — where a PDF opens, and why.
//
// Three decisions, each a plain function over its inputs:
//
//   htmlTwinOf()     — which address would be this PDF's real HTML rendering;
//   twinExists()     — whether that page was ever built (over an injected fetch, so the
//                      suite never touches the network);
//   shouldAutoOpen() — whether a PDF tab may turn itself into the reading mode.
//
// The probe answers here are the ones arxiv.org really gave on 2026-09-19: a converted
// paper is 200/206 `text/html` whose first bytes carry the LaTeXML marker, and a paper
// that was never converted — physics/0004090, quant-ph/9605043, a version that does not
// exist, a nonsense id — is a 404 carrying arXiv's own error page.
import { describe, expect, it } from "vitest";
import { htmlTwinOf } from "../../lib/pdf/source";
import {
  createTwinResolver,
  shouldAutoOpen,
  twinExists,
  TWIN_PREFIX_BYTES,
  TWIN_TIMEOUT_MS,
  type AutoOpenFacts,
} from "../../lib/pdf/route";

describe("the HTML twin of a PDF address", () => {
  it.each([
    // The forms arXiv's own pages and everybody else's links really use.
    ["https://arxiv.org/pdf/2301.10226", "https://arxiv.org/html/2301.10226"],
    ["https://arxiv.org/pdf/2301.10226v7", "https://arxiv.org/html/2301.10226v7"],
    ["https://arxiv.org/pdf/2301.10226v7.pdf", "https://arxiv.org/html/2301.10226v7"],
    ["https://arxiv.org/pdf/2301.10226.pdf", "https://arxiv.org/html/2301.10226"],
    ["https://arxiv.org/pdf/2402.17764?download=true", "https://arxiv.org/html/2402.17764"],
    ["http://arxiv.org/pdf/2402.17764", "https://arxiv.org/html/2402.17764"],
    // Five-digit ids (arXiv went to five in 2015) and the pre-2007 archive/number form.
    ["https://arxiv.org/pdf/1706.03762", "https://arxiv.org/html/1706.03762"],
    ["https://arxiv.org/pdf/hep-th/9901001v2", "https://arxiv.org/html/hep-th/9901001v2"],
    ["https://arxiv.org/pdf/hep-th/9901001.pdf", "https://arxiv.org/html/hep-th/9901001"],
    ["https://arxiv.org/pdf/math.AG/0601001", "https://arxiv.org/html/math.AG/0601001"],
    ["https://arxiv.org/pdf/cond-mat.stat-mech/0703041v2", "https://arxiv.org/html/cond-mat.stat-mech/0703041v2"],
    // The mirrors are the same repository; the paper is asked for from arxiv.org itself.
    ["https://www.arxiv.org/pdf/2301.10226", "https://arxiv.org/html/2301.10226"],
    ["https://export.arxiv.org/pdf/2301.10226v1", "https://arxiv.org/html/2301.10226v1"],
    ["https://ARXIV.ORG/pdf/2301.10226", "https://arxiv.org/html/2301.10226"],
  ])("%s → %s", (pdf, html) => {
    expect(htmlTwinOf(pdf)).toBe(html);
  });

  it.each([
    // Already HTML — the walker reads it where it stands.
    ["https://arxiv.org/abs/2301.10226"],
    ["https://arxiv.org/html/2301.10226"],
    // Not arXiv, however much the address would like to look like it.
    ["https://notarxiv.org/pdf/2301.10226"],
    ["https://arxiv.org.evil.example/pdf/2301.10226"],
    ["https://evil.example/pdf/2301.10226?host=arxiv.org"],
    ["https://example.com/papers/2301.10226.pdf"],
    // arXiv, but not a paper's PDF.
    ["https://arxiv.org/pdf/"],
    ["https://arxiv.org/pdf/2301.10226v7/supplement"],
    ["https://arxiv.org/format/2301.10226"],
    ["https://arxiv.org/pdf/not-an-id"],
    ["https://arxiv.org/pdf/230.1022"],
    // Nothing the reading mode could hand back to a publisher anyway.
    ["file:///Users/someone/2301.10226.pdf"],
    ["blob:https://arxiv.org/8f0c-4a11"],
    ["not a url at all"],
    [""],
  ])("%s → null", (pdf) => {
    expect(htmlTwinOf(pdf)).toBeNull();
  });
});

// ---- does that page exist? ----------------------------------------------------------------

/** A LaTeXML page's first bytes, as arXiv really serves them. */
const PAPER =
  '<!DOCTYPE html><html lang="en">\n<head>\n<title>The Era of 1-bit LLMs</title>\n' +
  "<!--Generated by LaTeXML oxide (version 0.7.6) http://dlmf.nist.gov/LaTeXML/.-->\n";

/** arXiv's own error page: no marker anywhere in it. Served as 404 today. */
const NO_PAPER = '<!DOCTYPE html>\n<html lang="en">\n<head>\n<title> | arXiv e-print repository</title>\n';

function answer(status: number, body: string, type = "text/html; charset=utf-8"): Response {
  return new Response(body, { status, headers: { "content-type": type } });
}

/** A stand-in for the fetch the worker injects, with a record of what was asked for. */
function stub(handler: (url: string, init: RequestInit) => Promise<Response>) {
  const calls: { url: string; init: RequestInit }[] = [];
  const fetch = ((input: unknown, init?: RequestInit) => {
    calls.push({ url: String(input), init: init ?? {} });
    return handler(String(input), init ?? {});
  }) as typeof globalThis.fetch;
  return { fetch, calls };
}

describe("whether the twin was really built", () => {
  it("says yes to a converted paper, and asks for its first bytes only", async () => {
    const { fetch, calls } = stub(async () => answer(206, PAPER));
    expect(await twinExists("https://arxiv.org/html/2402.17764", { fetch })).toBe(true);
    const { headers, credentials } = calls[0].init;
    expect((headers as Record<string, string>).Range).toBe(`bytes=0-${TWIN_PREFIX_BYTES - 1}`);
    expect(credentials).toBe("omit");
  });

  it("says no to a paper arXiv never converted", async () => {
    const { fetch } = stub(async () => answer(404, NO_PAPER));
    expect(await twinExists("https://arxiv.org/html/physics/0004090", { fetch })).toBe(false);
  });

  it("says no to a 200 that is not a paper — a stub would otherwise read as one", async () => {
    const { fetch } = stub(async () => answer(200, NO_PAPER));
    expect(await twinExists("https://arxiv.org/html/1234.56789", { fetch })).toBe(false);
  });

  it("says no when the answer is not HTML at all", async () => {
    const { fetch } = stub(async () => answer(200, PAPER, "application/pdf"));
    expect(await twinExists("https://arxiv.org/html/1234.56789", { fetch })).toBe(false);
  });

  it("gives up at the deadline rather than leaving a click waiting", async () => {
    // Nothing ever answers: only the abort ends it, which is the rule the timeout exists
    // for — a reader who clicked is waiting, and the reading mode is a fine answer.
    const { fetch } = stub(
      (_url, init) =>
        new Promise<Response>((_resolve, reject) => {
          init.signal?.addEventListener("abort", () => reject(new Error("aborted")));
        }),
    );
    const started = Date.now();
    expect(await twinExists("https://arxiv.org/html/2402.17764", { fetch, timeoutMs: 40 })).toBe(false);
    expect(Date.now() - started).toBeLessThan(2000);
    expect(TWIN_TIMEOUT_MS).toBe(2500);
  });

  it("says no when the network says nothing", async () => {
    const { fetch } = stub(async () => {
      throw new TypeError("Failed to fetch");
    });
    expect(await twinExists("https://arxiv.org/html/2402.17764", { fetch })).toBe(false);
  });

  it("stops reading after the prefix instead of downloading half a megabyte", async () => {
    let pulled = 0;
    let cancelled = false;
    const chunk = new TextEncoder().encode(PAPER.padEnd(1024, " ").slice(0, 1024));
    const body = new ReadableStream<Uint8Array>({
      pull(controller) {
        pulled++;
        controller.enqueue(chunk); // half a megabyte of paper, if anybody asked for it all
      },
      cancel() {
        cancelled = true;
      },
    });
    const { fetch } = stub(
      async () => new Response(body, { status: 206, headers: { "content-type": "text/html" } }),
    );
    expect(await twinExists("https://arxiv.org/html/2402.17764", { fetch })).toBe(true);
    expect(pulled).toBeLessThanOrEqual(TWIN_PREFIX_BYTES / 1024 + 2);
    expect(cancelled).toBe(true);
  });
});

describe("resolving a PDF to the page it should really open", () => {
  it("asks about a paper once and remembers the answer", async () => {
    const { fetch, calls } = stub(async () => answer(206, PAPER));
    const resolve = createTwinResolver({ fetch });
    expect(await resolve("https://arxiv.org/pdf/2402.17764v1")).toBe("https://arxiv.org/html/2402.17764v1");
    expect(await resolve("https://arxiv.org/pdf/2402.17764v1.pdf")).toBe("https://arxiv.org/html/2402.17764v1");
    expect(calls).toHaveLength(1);
  });

  it("makes one request when the same paper is asked for twice in the same moment", async () => {
    const { fetch, calls } = stub(async () => answer(206, PAPER));
    const resolve = createTwinResolver({ fetch });
    const both = await Promise.all([
      resolve("https://export.arxiv.org/pdf/2402.17764"),
      resolve("https://arxiv.org/pdf/2402.17764"),
    ]);
    expect(both).toEqual(["https://arxiv.org/html/2402.17764", "https://arxiv.org/html/2402.17764"]);
    expect(calls).toHaveLength(1);
  });

  it("contacts nobody at all for a PDF that is not a paper we know", async () => {
    const { fetch, calls } = stub(async () => answer(206, PAPER));
    const resolve = createTwinResolver({ fetch });
    expect(await resolve("https://example.com/report.pdf")).toBeNull();
    expect(calls).toHaveLength(0);
  });

  it("falls back to the reading mode for a paper with no HTML", async () => {
    const { fetch, calls } = stub(async () => answer(404, NO_PAPER));
    const resolve = createTwinResolver({ fetch });
    expect(await resolve("https://arxiv.org/pdf/physics/0004090")).toBeNull();
    expect(calls[0].url).toBe("https://arxiv.org/html/physics/0004090");
  });
});

// ---- may a PDF tab open itself? -------------------------------------------------------------

describe("the automatic route", () => {
  /** A PDF tab as it arrives with the setting on and nothing in the way. */
  const ordinary: AutoOpenFacts = {
    setting: true,
    contentType: "application/pdf",
    protocol: "https:",
    navigationType: "navigate",
    frame: 0,
    pass: false,
  };

  it("opens an ordinary PDF tab when the setting is on", () => {
    expect(shouldAutoOpen(ordinary)).toBe(true);
    expect(shouldAutoOpen({ ...ordinary, protocol: "http:" })).toBe(true);
    // A local PDF too: the tick that lets a content script run on file URLs is the same
    // one that lets the reader fetch them, so where this is asked at all it can be done.
    expect(shouldAutoOpen({ ...ordinary, protocol: "file:" })).toBe(true);
    // A reload of the PDF itself is an ordinary visit; the reader's own URL reloads as
    // the reader, which never reaches this decision at all.
    expect(shouldAutoOpen({ ...ordinary, navigationType: "reload" })).toBe(true);
  });

  it.each([
    ["the setting is off", { setting: false }],
    ["the document is not a PDF", { contentType: "text/html" }],
    ["the reader pressed Back out of the reading mode", { navigationType: "back_forward" }],
    ["the reader is on its way to the original", { pass: true }],
    ["the PDF is somebody's iframe, not the tab", { frame: 3 }],
    ["the PDF exists only in this tab (blob:)", { protocol: "blob:" }],
    ["the PDF exists only in this tab (data:)", { protocol: "data:" }],
    ["the tab is showing something that is not a document at all", { protocol: "about:" }],
  ])("leaves the tab alone when %s", (_why, override) => {
    expect(shouldAutoOpen({ ...ordinary, ...override })).toBe(false);
  });
});
