// test/node/scale.test.ts — the word, the colour and the doubt a verdict is shown with.
import { describe, expect, it } from "vitest";
import type { ScoreResult } from "../../lib/contract";
import { band, isFlagged } from "../../lib/render/band";
import { levelOf, scaleColor, scaleStep, SCALE_STEPS, SCORE_CUTS, scoreRange, spread } from "../../lib/render/scale";

const result = (percent: number[]): ScoreResult => {
  const probs = percent.map((p) => p / 100);
  const score = probs.reduce((acc, p, i) => acc + p * i, 0) / 3;
  const bucket = probs.indexOf(Math.max(...probs));
  return { id: "x", bucket, probs, score };
};
const lightness = (css: string): number => Number(/oklch\(([\d.]+)/.exec(css)![1]);

describe("the word follows the score", () => {
  it("cuts where EditLens's equal buckets meet: 1/6, 1/2, 5/6", () => {
    expect(SCORE_CUTS).toEqual([1 / 6, 1 / 2, 5 / 6]);
    expect([0, 0.16, 1 / 6, 0.49, 0.5, 0.83, 5 / 6, 1].map(levelOf)).toEqual([0, 0, 1, 1, 2, 2, 3, 3]);
    expect(levelOf(Number.NaN)).toBe(0);
  });

  it("is the bucket whose slice holds the score, not the most likely bucket", () => {
    // Measured on arXiv 2609.20794: coloured AI-generated by one point, while its number sat mid-scale.
    const abstract = result([15, 33, 18, 34]);
    expect(abstract.bucket).toBe(3);
    expect(band(abstract)).toBe("heavy");
    // .63 with lightly edited on top (35%): the old label contradicted its own number.
    const probe = result([4, 35, 30, 31]);
    expect(probe.bucket).toBe(1);
    expect(band(probe)).toBe("heavy");
    expect(band(result([88, 9, 2, 1]))).toBe("human");
    expect(band(result([1, 5, 9, 85]))).toBe("ai");
  });

  it("flags AI-generated verdicts only, exactly where the word turns to AI-generated", () => {
    expect(isFlagged({ id: "x", bucket: 3, probs: [0, 0, 0.5, 0.5], score: 5 / 6 })).toBe(true);
    expect(isFlagged({ id: "x", bucket: 2, probs: [0, 0.02, 0.5, 0.48], score: 0.8267 })).toBe(false);
    expect(isFlagged({ id: "x", bucket: 2, probs: [0, 0.2, 0.6, 0.2], score: 2 / 3 })).toBe(false);
  });

  it("keeps the two verdicts that are not verdicts", () => {
    expect(band({ ...result([0, 0, 0, 100]), degraded: true })).toBe("unknown");
    expect(band({ ...result([0, 0, 0, 100]), unsupported: true })).toBe("unsupported");
  });
});

describe("the colour", () => {
  it("runs one way: darker with every step on a light page, brighter on a dark one", () => {
    for (const dark of [false, true]) {
      const steps = Array.from({ length: SCALE_STEPS + 1 }, (_, i) => lightness(scaleColor(i / SCALE_STEPS, dark)));
      for (let i = 1; i < steps.length; i++) {
        if (dark) expect(steps[i]).toBeGreaterThan(steps[i - 1]);
        else expect(steps[i]).toBeLessThan(steps[i - 1]);
      }
    }
  });

  it("is continuous: two scores either side of a word's edge are one step apart at most", () => {
    expect(Math.abs(scaleStep(0.49) - scaleStep(0.51))).toBeLessThanOrEqual(1);
    expect(scaleStep(-1)).toBe(0);
    expect(scaleStep(2)).toBe(SCALE_STEPS);
    expect(scaleColor(0.3, false, 0.2)).toMatch(/\/ 0\.2\)$/);
  });
});

describe("the doubt", () => {
  it("measures spread around the mean on the ordered scale", () => {
    expect(spread([1, 0, 0, 0])).toBe(0);
    expect(spread([0.5, 0, 0, 0.5])).toBeCloseTo(1);
    // Half on two neighbours is "in between", not "no idea".
    expect(spread([0, 0.5, 0.5, 0])).toBeLessThan(spread([0.5, 0, 0, 0.5]) / 2);
  });

  it("orders verdicts by how split they are, with no threshold between them", () => {
    const [split, leaning, sure] = [[15, 33, 18, 34], [61, 29, 7, 3], [1, 5, 9, 85]].map((p) => spread(result(p).probs));
    expect(split).toBeGreaterThan(leaning);
    expect(leaning).toBeGreaterThan(sure);
  });

  it("shades a range that holds the score and stays on the scale", () => {
    const r = result([15, 33, 18, 34]);
    const range = scoreRange(r);
    expect(range.from).toBeLessThan(r.score);
    expect(range.to).toBeGreaterThan(r.score);
    const edge = scoreRange(result([0, 0, 0, 100]));
    expect(edge).toEqual({ from: 1, to: 1 });
  });
});
