// test/node/scale.test.ts — the word, the colour and the doubt a verdict is shown with.
import { describe, expect, it } from "vitest";
import { lrgb, oklab, parse, wcagContrast } from "culori";
import type { ScoreResult } from "../../lib/contract";
import { band, flagFromOf, isFlagged } from "../../lib/render/band";
import { BAND_COLORS, bandColor, levelOf, nearestOtherLevel, scaleColor, scaleGradient, scaleStep, SCALE_STEPS, SCORE_CUTS, spread } from "../../lib/render/scale";

const result = (percent: number[]): ScoreResult => {
  const probs = percent.map((p) => p / 100);
  const score = probs.reduce((acc, p, i) => acc + p * i, 0) / 3;
  const bucket = probs.indexOf(Math.max(...probs));
  return { id: "x", bucket, probs, score };
};

describe("the word follows the score", () => {
  it("cuts where EditLens's equal buckets meet: 1/6, 1/2, 5/6", () => {
    expect(SCORE_CUTS).toEqual([1 / 6, 1 / 2, 5 / 6]);
    expect([0, 0.16, 1 / 6, 0.49, 0.5, 0.83, 5 / 6, 1].map(levelOf)).toEqual([0, 0, 1, 1, 2, 2, 3, 3]);
    expect(levelOf(Number.NaN)).toBe(0);
  });

  it("is the bucket whose slice holds the score, not the most likely bucket", () => {
    // Measured on arXiv 2609.20794: coloured AI-generated by one point, while its number sat mid-scale.
    const abstract = result([15, 33, 18, 34]);
    expect(abstract.bucket).toBe(3);
    expect(band(abstract)).toBe("heavy");
    // .63 with lightly edited on top (35%): the old label contradicted its own number.
    const probe = result([4, 35, 30, 31]);
    expect(probe.bucket).toBe(1);
    expect(band(probe)).toBe("heavy");
    expect(band(result([88, 9, 2, 1]))).toBe("human");
    expect(band(result([1, 5, 9, 85]))).toBe("ai");
  });

  it("flags from the word Settings names, exactly where the word turns: Heavily edited unless said", () => {
    const at = (score: number) => ({ id: "x", bucket: 2, probs: [0, 0, 1, 0], score });
    // The default: Heavily edited and AI-generated.
    expect(isFlagged(at(5 / 6))).toBe(true);
    expect(isFlagged(at(0.5))).toBe(true);
    expect(isFlagged(at(0.4999))).toBe(false);
    // AI-generated only: exactly where the word turns to AI-generated.
    expect(isFlagged(at(5 / 6), "ai")).toBe(true);
    expect(isFlagged(at(0.8267), "ai")).toBe(false);
    // Lightly edited and above, from .17; Human never.
    expect(isFlagged(at(1 / 6), "light")).toBe(true);
    expect(isFlagged(at(0.16), "light")).toBe(false);
    // Neither a failure nor another language is ever flagged, from any word.
    for (const from of ["light", "heavy", "ai"] as const) {
      expect(isFlagged({ ...at(1), degraded: true }, from)).toBe(false);
      expect(isFlagged({ ...at(1), unsupported: true }, from)).toBe(false);
    }
    // A stored value that is none of the three reads as the default.
    expect(flagFromOf("nonsense")).toBe("heavy");
    expect(flagFromOf(undefined)).toBe("heavy");
  });

  it("keeps the two verdicts that are not verdicts", () => {
    expect(band({ ...result([0, 0, 0, 100]), degraded: true })).toBe("unknown");
    expect(band({ ...result([0, 0, 0, 100]), unsupported: true })).toBe("unsupported");
  });
});

describe("the colour", () => {
  it("is the word's: four colours, one per word, and nothing in between", () => {
    for (const dark of [false, true]) {
      const own = dark ? BAND_COLORS.dark : BAND_COLORS.light;
      expect([0, 0.16, 1 / 6, 0.3, 0.49, 0.5, 0.83, 5 / 6, 1].map((s) => scaleColor(s, dark)))
        .toEqual([own[0], own[0], own[1], own[1], own[1], own[2], own[2], own[3], own[3]]);
      expect(new Set(own).size).toBe(4);
    }
    expect(bandColor(3, false, 0.2)).toMatch(/^rgb\(\d+ \d+ \d+ \/ 0\.2\)$/);
  });

  it("keeps every two words apart, also for a reader with protanopia or deuteranopia", () => {
    // Machado, Oliveira and Fernandes 2009, full severity, on linear sRGB.
    const MACHADO = {
      protanopia: [[0.152286, 1.052583, -0.204868], [0.114503, 0.786281, 0.099216], [-0.003882, -0.048116, 1.051998]],
      deuteranopia: [[0.367322, 0.860646, -0.227968], [0.280085, 0.672501, 0.047413], [-0.01182, 0.04294, 0.968881]],
    } as const;
    const seen = (css: string, kind?: keyof typeof MACHADO) => {
      if (!kind) return oklab(parse(css)!);
      const c = lrgb(parse(css)!);
      const v = [c.r, c.g, c.b];
      const [r, g, b] = MACHADO[kind].map((row) => Math.min(1, Math.max(0, row[0] * v[0]! + row[1] * v[1]! + row[2] * v[2]!)));
      return oklab({ mode: "lrgb", r: r!, g: g!, b: b! });
    };
    for (const [dark, normal, cvd] of [[false, 15, 8.5], [true, 13, 9]] as const) {
      const colours = dark ? BAND_COLORS.dark : BAND_COLORS.light;
      for (const kind of [undefined, "protanopia", "deuteranopia"] as const) {
        const least = kind ? cvd : normal;
        for (let i = 0; i < 4; i++) for (let j = i + 1; j < 4; j++) {
          const a = seen(colours[i]!, kind), b = seen(colours[j]!, kind);
          const d = 100 * Math.hypot(a.l - b.l, a.a - b.a, a.b - b.b);
          expect(d, `${dark ? "dark" : "light"} ${kind ?? "normal"} ${i}-${j}`).toBeGreaterThanOrEqual(least);
        }
      }
    }
  });

  it("reads on its page: a mark on white or on near-black", () => {
    // The gold is the one light colour under 3:1 on white; it is a gold, and the word is beside it.
    expect(BAND_COLORS.light.map((c) => wcagContrast(c, "#ffffff") >= 3)).toEqual([true, false, true, true]);
    expect(wcagContrast(BAND_COLORS.light[1], "#ffffff")).toBeGreaterThan(2);
    for (const c of BAND_COLORS.dark) expect(wcagContrast(c, "#171717")).toBeGreaterThan(4.5);
  });

  it("draws the scale as the four words over their slices, cut where the words change", () => {
    expect(scaleGradient(false)).toBe(
      `linear-gradient(to right, ${BAND_COLORS.light[0]} 0 16.67%, ${BAND_COLORS.light[1]} 16.67% 50.00%, ${BAND_COLORS.light[2]} 50.00% 83.33%, ${BAND_COLORS.light[3]} 83.33% 100%)`,
    );
  });

  it("underlines in one named step per word", () => {
    expect(SCALE_STEPS).toBe(3);
    expect([-1, 0.1, 0.3, 0.6, 0.9, 2].map(scaleStep)).toEqual([0, 0, 1, 2, 3, 3]);
  });
});

describe("the doubt", () => {
  it("measures spread around the mean on the ordered scale", () => {
    expect(spread([1, 0, 0, 0])).toBe(0);
    expect(spread([0.5, 0, 0, 0.5])).toBeCloseTo(1);
    // Half on two neighbours is "in between", not "no idea".
    expect(spread([0, 0.5, 0.5, 0])).toBeLessThan(spread([0.5, 0, 0, 0.5]) / 2);
  });

  it("orders verdicts by how split they are, with no threshold between them", () => {
    const [split, leaning, sure] = [[15, 33, 18, 34], [61, 29, 7, 3], [1, 5, 9, 85]].map((p) => spread(result(p).probs)) as [number, number, number];
    expect(split).toBeGreaterThan(leaning);
    expect(leaning).toBeGreaterThan(sure);
  });

  it("names the word an unsure verdict lies nearest to", () => {
    expect([0.05, 0.15, 0.2, 0.45, 0.55, 0.8, 0.9].map(nearestOtherLevel)).toEqual([1, 1, 0, 2, 1, 3, 2]);
  });

});
