import { defineConfig } from "wxt";

// WXT config: manifest keys, permissions, targets.
// Icons are generated by `node test/genicons.mjs` into public/icons/.
export default defineConfig({
  // Build into ./output (not WXT's default ./.output) so it's visible in Finder.
  outDir: "output",
  manifest: {
    name: "Pangram AI Detector",
    description: "Per-paragraph AI-generated-text confidence badges.",
    permissions: ["storage", "activeTab"],
    host_permissions: ["<all_urls>"],
    icons: {
      16: "icons/icon-16.png",
      48: "icons/icon-48.png",
      128: "icons/icon-128.png",
    },
    action: {
      default_popup: "popup/index.html",
      default_title: "Pangram AI Detector",
    },
  },
});
