import { defineConfig } from "wxt";

// WXT config: manifest keys, permissions, targets.
// Icons are generated by `node test/genicons.mjs` into public/icons/.
export default defineConfig({
  // Build into ./output (not WXT's default ./.output) so it's visible in Finder.
  outDir: "output",
  manifest: ({ browser }) => {
    const productName = browser === "firefox" ? "Anagram for Firefox" : "Anagram for Chrome";
    return {
      name: productName,
      description: "Per-paragraph AI-generated-text confidence badges.",
      permissions: ["storage", "activeTab", "contextMenus"],
      ...(browser === "firefox"
        ? {
            browser_specific_settings: {
              gecko: {
                id: "anagram@coderbak.dev",
                // Intl.Segmenter 125, zoom 126; underlines feature-detect (140+).
                strict_min_version: "128.0",
                // AMO's data-collection disclosure: nothing is collected or transmitted.
                data_collection_permissions: { required: ["none"] },
              },
            },
          }
        : {}),
      commands: {
        "toggle-overlay": {
          suggested_key: { default: "Alt+Shift+P" },
          description: "Show/hide Anagram badges",
        },
      },
      host_permissions: ["<all_urls>"],
      // On-demand vendor chunks (Readability, DOMPurify) are import()ed by URL from
      // content scripts — see lib/lazy.ts and scripts/vendor.mjs.
      web_accessible_resources: [{ resources: ["vendor/*"], matches: ["<all_urls>"] }],
      icons: {
        16: "icons/icon-16.png",
        48: "icons/icon-48.png",
        128: "icons/icon-128.png",
      },
      action: {
        default_popup: "popup/index.html",
        default_title: productName,
      },
    };
  },
});
