// scripts/flavor.mjs — which Anagram a build makes.
//
//   native    (the default) scores through the local engine that `install.sh` sets up,
//             over Native Messaging.
//   oneclick  runs the same pinned model inside the browser, in an offscreen document with
//             ONNX Runtime Web; there is nothing to install beside the extension.
//
// The flavor is ANAGRAM_FLAVOR at build time, unset meaning native, so every existing
// command builds exactly what it built before. `node scripts/oneclick.mjs <command>` runs a
// command as the oneclick flavor; package.json's *:oneclick scripts are that.
//
// Not a WXT mode: WXT sets NODE_ENV to the mode's name, which would build dependencies'
// development branches and a pretty-printed manifest. The flavor is a define instead
// (import.meta.env.ANAGRAM_FLAVOR), plus the module swaps below.
import { resolve } from "node:path";

export const FLAVORS = ["native", "oneclick"];

/** The flavor `env` asks for. An unknown one fails rather than building the default. */
export function flavorOf(env = process.env) {
  const flavor = env.ANAGRAM_FLAVOR || "native";
  if (!FLAVORS.includes(flavor)) throw new Error(`ANAGRAM_FLAVOR=${flavor}: expected one of ${FLAVORS.join(", ")}`);
  return flavor;
}

/**
 * Import specifiers that name a different module in each flavor. Code imports the
 * specifier; the build (a WXT alias, so Vite and the generated tsconfig agree) links that
 * flavor's module and never reads the other one, so neither flavor carries the other's
 * code or its messages. Both modules export the same names with the same types.
 */
export const FLAVOR_MODULES = {
  // The engine the background worker sends contract operations to: `engineTransport()`.
  "#flavor/engine-transport": { native: "lib/backend/nativeTransport.ts", oneclick: "lib/webengine/client.ts" },
  // The engine panel on the setup page and in Settings.
  "#flavor/engine-panel": { native: "lib/ui/componentSettings.ts", oneclick: "lib/ui/inBrowserEngine.ts" },
};

/** `FLAVOR_MODULES` resolved for one flavor: specifier → absolute file. */
export function flavorAliases(flavor, root) {
  return Object.fromEntries(Object.entries(FLAVOR_MODULES).map(([spec, files]) => [spec, resolve(root, files[flavor])]));
}

/** Entrypoints (entrypoints/<name>) only one flavor builds; every other one both build. */
export const FLAVOR_ENTRYPOINTS = {
  // The offscreen document the in-browser engine runs in.
  engine: "oneclick",
};

/** Does `flavor` build the entrypoint called `name`? */
export function buildsEntrypoint(flavor, name) {
  return (FLAVOR_ENTRYPOINTS[name] ?? flavor) === flavor;
}

/** Where WXT writes a flavor's build under output/ (or output-test/): WXT's own
 *  `<browser>-mv<n>` for native, as always, and the same with a prefix for oneclick. */
export function outDirTemplate(flavor) {
  return flavor === "native" ? undefined : `${flavor}-{{browser}}-mv{{manifestVersion}}`;
}

/** The folder of a built target under output/: `outputDir("oneclick", "chrome", 3)`. */
export function outputDir(flavor, browser, manifestVersion) {
  return `${flavor === "native" ? "" : `${flavor}-`}${browser}-mv${manifestVersion}`;
}

/** Files only the oneclick flavor ships, generated by scripts/vendor.mjs and copied into
 *  that flavor's builds by wxt.config.ts: public/ goes into every build. */
export const ONECLICK_PUBLIC = "public-oneclick";
