// Pin the complete Mozilla generic viewer, while keeping Anagram's integration separate.
import { createHash } from "node:crypto";
import { cpSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export function vendorPdfViewer(root) {
  const pin = JSON.parse(readFileSync(join(root, "vendor/pdfjs/upstream.json"), "utf8"));
  const installed = JSON.parse(readFileSync(join(root, "node_modules/pdfjs-dist/package.json"), "utf8")).version;
  if (installed !== pin.version) throw new Error(`PDF.js viewer ${pin.version} must match installed engine ${installed}`);
  const source = join(root, "vendor/pdfjs", pin.version);
  const list = (dir, prefix = "") => readdirSync(dir, {withFileTypes:true}).flatMap((entry) => {
    const name = prefix + entry.name;
    return entry.isDirectory() ? list(join(dir, entry.name), `${name}/`) : [name];
  });
  if (JSON.stringify(list(source).sort()) !== JSON.stringify(Object.keys(pin.files).sort()))
    throw new Error("PDF.js upstream file inventory does not match its pin");
  for (const [name, expected] of Object.entries(pin.files)) {
    const digest = createHash("sha256").update(readFileSync(join(source, name))).digest("hex");
    if (digest !== expected) throw new Error(`Modified upstream PDF.js asset: ${name}`);
  }
  const output = join(root, "public/vendor/pdfjs");
  rmSync(output, {recursive:true, force:true});
  mkdirSync(join(output, "web"), {recursive:true});
  for (const name of ["viewer.mjs", "viewer.css", "images", "locale"])
    cpSync(join(source, "web", name), join(output, "web", name), {recursive:true});
  cpSync(join(source, "LICENSE"), join(output, "LICENSE"));

  let html = readFileSync(join(source, "web/viewer.html"), "utf8").replace(/^\uFEFF/, "");
  const replace = (before, after) => {
    if (!html.includes(before)) throw new Error(`PDF.js template changed: ${before}`);
    html = html.replace(before, after);
  };
  replace('<meta charset="utf-8" />', '<meta charset="utf-8" />\n    <meta http-equiv="Content-Security-Policy" content="connect-src \'self\'" />');
  replace('href="locale/locale.json"', 'href="/vendor/pdfjs/web/locale/locale.json"');
  replace('href="viewer.css"', 'href="/vendor/pdfjs/web/viewer.css"');
  replace('<script src="../build/pdf.mjs" type="module"></script>', '<!-- Engine and viewer initialization are owned by main.ts. -->');
  replace('<script src="viewer.mjs" type="module"></script>', '<script src="./main.ts" type="module"></script>');
  // WXT normalizes interactive input children out of buttons; retain their upstream hidden intent.
  replace('<input id="viewsManagerAddFilePicker" type="file" accept="application/pdf" />',
    '<input id="viewsManagerAddFilePicker" type="file" accept="application/pdf" hidden />');
  replace('<div id="toolbarViewerRight" class="toolbarHorizontalGroup">', `<div id="toolbarViewerRight" class="toolbarHorizontalGroup">
                <button id="anagramAnalyze" class="toolbarButton labeled" type="button" data-anagram="host"><span>Anagram</span></button>
                <button id="original" class="toolbarButton labeled" type="button" data-anagram="host" hidden><span></span></button>`);
  replace('<body tabindex="0">', `<body tabindex="0">
    <aside id="anagramReaderStatus" data-anagram="host" aria-live="polite">
      <p id="notice" role="status"></p>
      <section id="drop" hidden><p id="dropLabel"></p><button id="choose" type="button"></button><input id="file" type="file" accept="application/pdf,.pdf" hidden /></section>
    </aside>
    <p id="analysisScope" data-anagram="host" hidden></p>`);
  writeFileSync(join(root, "entrypoints/reader/index.html"), '<!-- Generated by scripts/pdfjsViewer.mjs from the pinned Mozilla viewer. -->\n' + html);
}
