// scripts/sigstoreLock.mjs — the Sigstore verifier the installers download, pinned.
//
// install.sh and install.ps1 verify a release's Sigstore bundle with sigstore-python, put into
// a throwaway environment from PyPI (or the person's mirror) with every file's hash required.
// What it is pinned to is installer/sigstore.in; this writes the locked list,
// installer/sigstore.txt: each package at the version uv resolves, with the hashes of only the
// wheels a CPython 3.12 can install on the platforms the installers run on — macOS on Apple
// Silicon, glibc Linux on x86-64 and ARM, Windows on x86-64 — one line each, so that the
// installers can carry the list (every hash of every file would be 600 lines). It copies the
// list into both installers between their markers; the release workflow installs the file
// itself to sign. It copies installer/verify_release.py, which the installers run with it,
// into both as well. test/node/sigstoreLock.test.ts holds every copy to its source.
//
//   node scripts/sigstoreLock.mjs     after changing installer/sigstore.in
//
// Network: PyPI's JSON API, for each pinned file's name and hash.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PYTHON = "3.12";
export const BEGIN = "# >>> generated by scripts/sigstoreLock.mjs from installer/sigstore.in";
export const END = "# <<< generated";
export const SCRIPT_BEGIN = "# >>> installer/verify_release.py, copied by scripts/sigstoreLock.mjs";
export const SCRIPT_END = "# <<< installer/verify_release.py";

/** `text` with what stands between `begin` and `end` (the two lines included) made `body`. */
export function embedded(text, begin, end, body, file) {
  const from = text.indexOf(begin), to = text.indexOf(end);
  if (from < 0 || to < from) throw new Error(`${file} has no ${begin} … ${end} block`);
  return text.slice(0, from) + body + text.slice(to + end.length);
}

/** The platforms the installers run on, by the platform tag a wheel names. */
const PLATFORMS = {
  "macOS arm64": (p) => /^macosx_\d+_\d+_(arm64|universal2)$/.test(p),
  "Linux x86-64": (p) => /^(manylinux\d*|manylinux_\d+_\d+)_x86_64$/.test(p),
  "Linux arm64": (p) => /^(manylinux\d*|manylinux_\d+_\d+)_aarch64$/.test(p),
  "Windows x86-64": (p) => p === "win_amd64",
};

/** Can CPython 3.12 run a wheel of these interpreter and ABI tags? */
function forPython(pythons, abi) {
  return pythons.some((py) =>
    ((py === "py3" || py === "py312") && abi === "none")
    || (py === "cp312" && (abi === "cp312" || abi === "abi3" || abi === "none"))
    || (/^cp3\d+$/.test(py) && abi === "abi3" && Number(py.slice(3)) <= 12));
}

/** The platforms a wheel's file name serves, of PLATFORMS ("any" serves them all). */
export function servesOf(filename) {
  const m = /^(.+?)-([^-]+)(?:-\d[^-]*)?-([^-]+)-([^-]+)-([^-]+)\.whl$/.exec(filename);
  if (!m) return [];
  const [, , , py, abi, plat] = m;
  if (!forPython(py.split("."), abi)) return [];
  const plats = plat.split(".");
  return Object.keys(PLATFORMS).filter((name) => plats.some((p) => p === "any" || PLATFORMS[name](p)));
}

async function main() {
  const pins = execFileSync("uv", ["pip", "compile", join(ROOT, "installer", "sigstore.in"), "--universal", "--python-version", PYTHON, "--no-header", "--no-annotate", "--quiet"], { encoding: "utf8" })
    .split("\n").map((l) => l.trim()).filter((l) => l && !l.startsWith("#"));
  const lines = [];
  for (const pin of pins) {
    const [spec, marker] = pin.split(/\s*;\s*/);
    const [name, version] = spec.split("==");
    const response = await fetch(`https://pypi.org/pypi/${name}/${version}/json`, { headers: { "User-Agent": "anagram-sigstore-lock" } });
    if (!response.ok) throw new Error(`PyPI has no ${name} ${version}: ${response.status}`);
    const files = (await response.json()).urls;
    const covered = new Set();
    const hashes = [];
    for (const file of files) {
      if (file.packagetype !== "bdist_wheel") continue;
      const serves = servesOf(file.filename);
      if (serves.length === 0) continue;
      serves.forEach((p) => covered.add(p));
      hashes.push(file.digests.sha256);
    }
    const missing = Object.keys(PLATFORMS).filter((p) => !covered.has(p));
    if (missing.length > 0) throw new Error(`${name} ${version} has no wheel for ${missing.join(", ")}`);
    lines.push(`${name}==${version}${marker ? ` ; ${marker}` : ""} ${hashes.sort().map((h) => `--hash=sha256:${h}`).join(" ")}`);
  }
  const body = [BEGIN, ...lines, END].join("\n");
  const pinned = readFileSync(join(ROOT, "installer", "sigstore.in"), "utf8").trim();
  writeFileSync(join(ROOT, "installer", "sigstore.txt"), `# sigstore-python and what it needs, for CPython ${PYTHON} (${pinned}).\n${body}\n`);
  const script = [SCRIPT_BEGIN, readFileSync(join(ROOT, "installer", "verify_release.py"), "utf8").trimEnd(), SCRIPT_END].join("\n");
  for (const file of ["install.sh", "install.ps1"]) {
    const path = join(ROOT, file);
    const text = readFileSync(path, "utf8");
    writeFileSync(path, embedded(embedded(text, BEGIN, END, body, file), SCRIPT_BEGIN, SCRIPT_END, script, file));
  }
  console.log(`${lines.length} packages pinned for ${Object.keys(PLATFORMS).join(", ")}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
